---
- name: Debian | Install ntp package
  ansible.builtin.apt:
    name: "chrony"
    state: present
    update_cache: true
    allow_unauthenticated: false
  become: true

- name: Debian | Configure ntp server on controllers
  ansible.builtin.template:
    dest: "/etc/chrony/chrony.conf"
    src: "etc/chrony/chrony.conf.j2"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify:
    - systemctl restart service
  when: inventory_hostname in groups['controller']

- name: Debian | Configure ntp client on others
  ansible.builtin.template:
    dest: "/etc/chrony/chrony.conf"
    src: "etc/chrony/chrony.conf.client.j2"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  notify:
    - systemctl restart service
  when: inventory_hostname not in groups['controller']
...
