---
- name: Delete | import common tasks
  tags:
    - ntp
    - pbos-infra
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | import stop tasks
  tags:
    - ntp
    - pbos-infra
  ansible.builtin.import_tasks: "stop.yml"

- name: Delete | remove packages
  tags:
    - ntp
    - pbos-infra
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop: "{{ packages }}"
  become: true

- name: Delete | remove directory
  tags:
    - ntp
    - pbos-infra
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/chrony
  become: true
...
