---
- name: Stop | include default variables
  tags: ntp
  ansible.builtin.include_vars: "../vars/main.yml"

- name: Stop | include os specific variables
  tags: ntp
  ansible.builtin.include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"

- name: stop service
  tags: ntp
  debug:
    msg: "Stop {{ service_name }} service."
  changed_when: true
  notify:
    - systemctl stop service
...
