---
- name: Ubuntu | Install ntp package
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ packages }}"

- name: Ubuntu | Configure ntp server on controllers
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  loop: "{{ service_conf }}"
  changed_when: true
  notify:
    - systemctl restart service
  when: inventory_hostname in groups['controller']

- name: Ubuntu | Configure ntp client on others
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.client.j2' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  loop: "{{ service_conf }}"
  changed_when: true
  notify:
    - systemctl restart service
  when: inventory_hostname not in groups['controller']
...
